In [51]:
import numpy as np
import scipy.linalg

In [2]:
covar = np.reshape(np.loadtxt('../10ns/com_covariance_matrix.dat'), (228, 228))

In [10]:
Q = np.reshape(np.loadtxt('../10ns/com_Rmatrix'), (228, 228))

In [28]:
traj = np.load('../unformatted_traj.npy')

In [30]:
straj = traj[:, :50000]

In [36]:
dtraj = np.copy(traj)

for i in range(traj.shape[0]):
    dtraj[i,:] = dtraj[i,:] - (traj.mean(1))[i]

In [37]:
xi = np.matmul(Q.T, dtraj[:,:50000])

In [33]:
np.dot(xi[0,:]**2, xi[0,:]**2) / xi.shape[1] - (np.dot(xi[0,:], xi[0,:]) / xi.shape[1])*(np.dot(xi[1,:], xi[1,:]) / xi.shape[1])

0.2927948336001244

In [42]:
U = np.load('../../tica/notebooks/1000microstates/lag2000.0/Umatrix.npy')

In [43]:
tICs = np.matmul(U.T, dtraj)

In [44]:
np.dot(tICs[0,:], tICs[1,:]) / tICs.shape[1]

-0.0002652765007811128

In [45]:
np.dot(tICs[0,:]**2, tICs[1,:]**2) / tICs.shape[1] - (np.dot(tICs[0,:], tICs[0,:]) / tICs.shape[1])*(np.dot(tICs[1,:], tICs[1,:]) / tICs.shape[1])

0.16455914835090113

In [46]:
V = np.load('../../tica/Vmatrix.npy')

In [58]:
dummy[-6:]

array([1.49441385e-13, 1.14399173e-13, 1.06610005e-13, 1.78461578e-16,
       1.57356086e-16, 9.55231267e-19])

In [62]:
dummy = abs(np.loadtxt('../com_covar_eig'))**-0.5
dummy[-6:] = 0

cov_eig = np.diag(dummy)

In [63]:
cov_eig

array([[1.21187759, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.7716173 , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 2.6682298 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [65]:
Vp = np.matmul(cov_eig, V)

In [69]:
np.matmul(Vp.T, V)

array([[200.05300122, 107.40016248,  -4.36160919, ...,   0.        ,
          0.        ,   0.        ],
       [107.40016248, 124.2668159 ,   5.56085091, ...,   0.        ,
          0.        ,   0.        ],
       [ -4.36160919,   5.56085091,  76.86049639, ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   1.21187759,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          1.7716173 ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   2.6682298 ]])